### ISSUE TITLE
Count command 

### ISSUE THREAD

**Issue by mhibti** [agpchil/mu4e-maildirs-extension#17] opened 2015-09-29 10:14 UTC
Hi every body,
Thanks for this extension. 
I have an issue with the count command, which  seems to fail with the message 

Unmatched '.

I have many buffers with this expression named mu4e-maildirs-extensionsXXXX...

I'm using mu4e - mu for emacs version 0.9.11 on emacs 25.
Thank you in advance,
Mohamed

**Comment by agpchil** [comment] 2015-09-29 10:30
Hi! Thanks for reporting your issue!

Can you tell me which version of `mu4e-maildirs-extension` are you using? installed from `melpa-stable`, `melpa` or manually (git master?)?

**Comment by agpchil** [comment] 2015-09-29 10:36
Also, do you have a maildir with a special char like `'`?

**Comment by mhibti** [comment] 2015-09-29 11:27
Thanks for this swift reply,
I'm using the elpa version (Package-Version: 20150923.559).
Some of the folders I have may contain special characters because of the french language. However, I customized mu4e-maildirs-extension-custom-list to avoid them.

**Comment by mhibti** [comment] 2015-09-29 16:57
The command (redirection) should not work with "/bin/csh". It worked with bash !!

**Comment by agpchil** [comment] 2015-09-29 18:48
You're right, looks like (t)csh don't support that redirection. Do you still get the `Unmatched '` error when running with bash?

I'll try to push a fix for this tomorrow.

**Comment by mhibti** [comment] 2015-09-30 08:20
No with bash no more errors.

**Comment by agpchil** [comment] 2015-09-30 09:51
Ok. But I don't like to require `bash` to make this work so I'll try to fix it anyway :-)

**Comment by agpchil** [comment] 2015-09-30 13:39
@mhibti I just pushed a quick fix to master.

With this changes, tcsh shell and maildirs with single quotes should work without customizing. But names with double-quote seems to need some extra escaping...

Should be available in MELPA in a couple of hours.
Let me know if it works for you!

**Comment by mhibti** [comment] 2015-09-30 13:42
Il will do as soon as possible!
Thanks

**Comment by mhibti** [comment] 2015-09-30 14:04
It didn't work. I guess the problem is not of the precompilation of the double quote  rather then a problem of redirection. The ">dev/null" should be fixed somehow. 
I found this which looks similar.

http://stackoverflow.com/questions/23164614/ambiguous-output-redirect-trying-to-send-both-stdout-and-stderr-to-mailx-from

**Comment by agpchil** [comment] 2015-09-30 14:16
There was 2 issues:
  1. The maildir was passed via `'%s'`, so if the maildir has a single-quote then it fails with unmatched. Now I changed using mu4e way, that means surrounded with `"%s"` so single-quote should not break (and backslashes and double-quote are escaped, although it needs more escaping to work...).

  2. The unsupported redirection of `stderr`. I changed the handler so it doesn't need to do the redirection but check the exit status instead.

It's weird because I tried with tcsh and a maildir with single-quotes (without any customization) and it worked for me. Be aware that MELPA takes some time to rebuild the packages (I belive the new version is not available yet).

Can you post the steps/config to reproduce the problem?

**Comment by mhibti** [comment] 2015-10-01 08:38
Hi Andreu,
I tried this morning and it worked. Great !!

**Comment by agpchil** [comment] 2015-10-01 12:52
Nice! I'm glad it finally worked :-)

I close this issue but feel free to open new issues if you need.

**Closed** 2015-10-01 12:52 UTC
