### ISSUE TITLE
Bookmark support?

### ISSUE THREAD

**Issue by nwolfe** [agpchil/mu4e-maildirs-extension#20] opened 2015-11-24 07:50 UTC
For each bookmark do a background query and show the unread/total results.
Basically, do the same thing for bookmarks as is done for maildirs.

Would this be reasonable to do, technically? 
Or perhaps this is a bit out of scope for this extension?

---

I really like this extension but I tend to have one or two maildirs and then several bookmarks (a.k.a saved searches), and I'd like to see the unread/total counts for those as well, or at least some of them.

**Comment by agpchil** [comment] 2015-11-24 11:01
This could be a bit tricky but I think it can be done!

The output you want is something like this?

```
  Bookmarks

	* [bu] Unread messages (3/3)
	* [bt] Today's messages (1/30)
	* [bw] Last 7 days (3/40)
	* [bi] Messages with images (0/10)

  Maildirs
	...
```

**Comment by nixmaniack** [comment] 2015-11-24 11:41
Oh yes! :+1: for this. Even I have only one maildir, but I have lots of bookmarks based on tags and I was trying to configure this using this package but couldn't figure out using the default search pattern. If this is implemented it'd be awesome!

**Comment by nwolfe** [comment] 2015-11-24 18:10
> The output you want is something like this?

Yes! That would be great.

Thank you for the quick response :metal:

**Comment by agpchil** [comment] 2015-11-27 09:40
I pushed the code in the `bookmarks` branch. Can you try and see if it works for you?
I had some ui issues so I changed the way the ui is updated from async to sync (but the data is still fetched async). You should be able to manually refresh the UI while fetching the data by pressing `g` (revert-buffer).

**Comment by agpchil** [comment] 2015-11-27 09:44
Forgot to say that the UI will be auto-updated when all the data is fetched.

**Comment by nwolfe** [comment] 2015-11-30 19:03
> Can you try and see if it works for you?

It works!  I didn't try it on an account with a bunch of bookmarks so I can't speak to the performance.
I do have some thoughts though:
* What about a setting to toggle on/off maildirs and bookmark support?

What if I don't want to see the maildirs anymore but instead just the bookmarks?  And I don't want to re-configure my email/mu4e to actually get rid of my maildirs, I just don't want the plugin to process them and render them.  Or perhaps somebody wants to keep things the way they are and not process bookmarks?  Maybe it's not possible/desirable to remove the Bookmarks section from the UI, but we could at least not draw the custom Maildirs section.

* Update the mu4e main page UI unread/total counts when I go back to the main page?

Not sure how feasible this is, but I'm thinking that it would be nice if the unread/total counts updated after I viewed the unread emails.  So, my routine/workflow would be: launch mu4e, see I have 6/25 messages in my Important bookmark, go to them (i.e. `bi` or something), read all 6, return to mu4e home page (i.e. `q`), and now see that I have 0/25 messages in my Important bookmark.

* Any chance this extension would ever be merged into mu4e proper?

Just curious, but it seems like this is generally desirable behavior to see how many emails you have in any given category (whether that's a maildir or a bookmark search).  Plus, if you add bookmark support then the plugin name `maildirs-extension` is less appropriate since it does more than that, but that's pretty minor :smile:

**Comment by agpchil** [comment] 2015-11-30 20:14
Great!

> What about a setting to toggle on/off maildirs and bookmark support?

I have this feature already in my todo list, hope to add it soon :)
It's a bit weird allowing to disable the maildirs section given that was the main purpose of this extension. But hey, why not ;)

> Update the mu4e main page UI unread/total counts when I go back to the main page?

(Note: This extension was fetching the data sync before, and was sloooooooow as hell. With the async support things got better but I think the default setting should be not so aggressive.) The UI is updated when the index is updated or by pressing `C-u C-u u` (yeah, I don't like that binding either). Anyway, I believe this can be done already using hooks (I've not tested this!):

```lisp
(defun my-mu4e-maildirs-extension-always-update ()
  (mu4e-maildirs-extension-force-update '(4)))

(add-hook 'mu4e-main-mode-hook 'my-mu4e-maildirs-extension-always-update)
```

But maybe I should made things easier...

> Any chance this extension would ever be merged into mu4e proper?

I'm not involved in mu4e development so... no idea :P
But honestly, I didn't even tried to get this merged into mu4e either...

> if you add bookmark support then the plugin name maildirs-extension is less appropriate

Well this extension name was poorly choosen anyway so it probably won't matter now :)

**Comment by nixmaniack** [comment] 2015-12-01 08:42
For me it partially worked or I'm missing something! 

<img width="312" alt="screen shot 2015-12-01 at 2 05 49 pm" src="https://cloud.githubusercontent.com/assets/542810/11495929/e12c875c-9834-11e5-9ec4-fad17fdad682.png">

The last 3 bookmarks do have messages in them unread/read. But don't seem to display it correctly. I didn't look at source to understand what's going on behind but I'm assuming you're concatenating with `flag:unread`? Can you point to me to debug this?

**Comment by agpchil** [comment] 2015-12-01 10:59
Thanks for testing!

`flag:unread` is added for the unread count. But I suspect the problem is the maildir param in the query. Can you post the value of your `mu4e-bookmarks` variable?

**Comment by nixmaniack** [comment] 2015-12-01 17:36
I don't use maildir actually in my bookmarks. Following is the value of `mu4e-bookmarks`.
```elisp
(("flag:unread AND NOT flag:trashed" "Unread messages" 97)
 ("date:today..now" "Today's messages" 116)
 ("date:7d..now" "Last 7 days" 119)
 ("mime:image/*" "Messages with images" 112)
 ("tag:\"\\\\Inbox\"" "Messages in Inbox" 105)
 ("tag:\"\\\\Inbox\" AND flag:unread AND NOT flag:trashed" "Unread Messages in Inbox" 117))
```

**Comment by agpchil** [comment] 2015-12-01 18:15
Well, I thought the problem was the `maildir:'/*'` that is being used internally for the bookmarks. But I think the issue is that the params of the queries are not properly escaped. Maybe surrounding them with single quotes will work?

```lisp
...
("mime:'image/*'" "Messages with images" 112)
("tag:'Inbox'" "Messages in Inbox" 105)
("tag:'Inbox' AND flag:unread AND NOT flag:trashed" "Unread Messages in Inbox" 117)
...
```
I can't test this right now so let me know if this workaround works for you.

**Comment by nixmaniack** [comment] 2015-12-01 20:17
Didn't seem to help using single quotes. The query I'm using is correct, actually I can drop the extra `""` I used around `Inbox` so following is same at works.
```elisp
...
("tag:\\\\Inbox" "Messages in Inbox" 105)
("tag:\\\\Inbox AND flag:unread AND NOT flag:trashed" "Unread Messages in Inbox" 117)
...
```
The `Inbox` label is in fact `\Inbox`, so mu expects it as `\\Inbox` and hence while passing through mu4e(emacs) we need to escape it.

**Comment by agpchil** [comment] 2015-12-01 20:42
Well, the query is called in a `shell-command` process, so the shell probably tries to interpret things (like the escape chars)... and kabom! (I didn't debug this yet, but I suspect this is what's happening).

But I'm a bit confused about the `mime:'image/*'`. I thought it would work, what about using escaped double quotes? 
`("mime:\"image/*\"" "Messages with images" 112)`

Anyway, I'll try to debug this when I have time and see if I can fix this escape madness...

**Comment by nixmaniack** [comment] 2015-12-01 21:06
Oh does that mean the query executed by `mu4e-headers-search` isn't same in this plugin? I generally use `s` i.e. `mu4e-headers-search` to make my bookmarks' query. 

mu4e seems to do it's own escaping while processing queries with `mu4e~proc-escape`. 

> what about using escaped double quotes? 

Executing this directly in `mu4e-headers-search` doesn't return anything, so I assume it won't serve the purpose even if it can rightly find unread/total count using this plugin which makes it unusable from mu4e home buffer. 

So I think maildirs-extension should try to create the same query as used by mu4e and modify it accordingly to find unread/total.

**Comment by nixmaniack** [comment] 2015-12-01 22:05
So using `("mime:'image/*'" "Messages with images" 112)` did turn up with numbers but as I said in previous comment this doesn't work with mu4e and I get nothing on entering that bookmark.

**Comment by agpchil** [comment] 2015-12-02 09:08
> So using ("mime:'image/*'" "Messages with images" 112) did turn up with numbers but as I said in previous comment this doesn't work with mu4e and I get nothing on entering that bookmark.

Yea, using single quotes was probably a bad suggestion. My fault. Anyway, the above ideas were just trying to find a lucky workaround, this package should handle this without requiring the user extra stuff.

> Oh does that mean the query executed by mu4e-headers-search isn't same in this plugin? I generally use s i.e. mu4e-headers-search to make my bookmarks' query.

Well, keep in mind this package was only adding the maildirs stuff initially. So there wasn't much of a user-query used. Now with bookmarks things are a bit different...

> mu4e seems to do it's own escaping while processing queries with mu4e~proc-escape

`mu4e~proc-escape` is also used here to escape the maildir name, but not for the bookmark query. Although the extra shell step doesn't help. This needs to be fixed... somehow :P

> So I think maildirs-extension should try to create the same query as used by mu4e and modify it accordingly to find unread/total.

I totally agree, and that would be great! But if I remember correctly, when I looked at mu4e internals, mu4e was processing the response of mu so if (for example) it detected a header response, it parsed and displayed the headers view directly. So reusing mu4e internals was not useful when trying to fetch the unread/total count. Using a shell-command was much easier (but also have its own problems). I could have missed something, or mu may have changed meanwhile too. Either way, emacs probably will struggle if it have to process the response (even if the call is made async) to count multiple queries with thousands of results...

I ended writing the extra async stuff anyways so it probably make sense to review this part again and see if I can use some of the mu4e internals here.

**Comment by nwolfe** [comment] 2015-12-04 07:31
> For me it partially worked or I'm missing something!
> screenshot
> The last 3 bookmarks do have messages in them unread/read. But don't seem to display it correctly.

I encountered this as well.  I noticed it was the wildcard I had in my search.  The UI wouldn't render correctly even though the bookmark would show the proper results.  The UI would just say `(0/0)`.

For example:
* Good: `list:group.foo.com`
* Bad: `list:group*`

**Comment by iqbalansari** [comment] 2015-12-05 17:18
> mu4e~proc-escape is also used here to escape the maildir name, but not for the bookmark query. Although the extra shell step doesn't help. This needs to be fixed... somehow

Since you are spawning a shell to get counts, `mu4e~proc-escape` would not help. I think the built-in Emacs function `shell-quote-argument`, is what you need.

I would really love this feature, thanks for working on this.

**Comment by nwolfe** [comment] 2015-12-10 01:02
:+1: again - been using this branch for a week or so now with no trouble really.

Only thing that comes to mind is every once in a while everything will update but it will think there are no unread messages; everything will be `(0/X)` and nothing is highlighted. When I jump to a bookmark myself though it seems to fix it and the mu4e home page is rendered with expected unread counts.

I just figure this is an oddity outside the scope of this extension, and certainly not a major concern (at least for me).

**Comment by nwolfe** [comment] 2015-12-10 01:08
It would be nice if we could fix the regex wildcard issue though https://github.com/agpchil/mu4e-maildirs-extension/issues/20#issuecomment-161898379

For now I'm just spelling out the full list URL like `list:foo.domain.com`, but this is annoying when there are multiple `foo*` lists like `foo-x.domain.com` and `foo-y.domain.com`.

I'd like to be able to capture results from all of `foo-x.domain.com` and `foo-y.domain.com` using just `list:foo-*` and not have to do `list:foo-x.domain.com AND list:foo-y.domain.com`

**Comment by agpchil** [comment] 2015-12-13 11:47
It's good to see more people getting involved here :)

I just pushed an attempt to fix this in the `bookmarks` branch. I couldn't test much this so give me some feedback please :)

@nixmaniack I quickly checked the mu4e code again and I see no way to reuse mu4e internals to fetch the counters. `mu4e` launches the `mu server` and listens all the replies and process them. AFAIK, only a single `mu server` can be run at the same time. But if you know a (better) way... let me know please :)

@iqbalansari I had no luck with `shell-quote-argument` so I ended up using `eshell-quote-argument` (I think I already tried `shell-quote-argument` in the past but can't remember). The thing about `shell-quote-argument` is that it tries to quote everything and messes the arguments for mu (mu read them as a single argument or something like that). The eshell quote looks more customizable... so I hope it works.

The user still needs to escape spaces in the names. But I believe that's how it works for mu searches anyway...

@nwolfe

> Only thing that comes to mind is every once in a while everything will update but it will think there are no unread messages; everything will be (0/X) and nothing is highlighted. When I jump to a bookmark myself though it seems to fix it and the mu4e home page is rendered with expected unread counts.

To me this looks like a bug in `mu4e-maildirs-extension`. Can you check if still happens with latest changes or provide a step-by-step way to reproduce the problem?

Thanks

**Comment by nixmaniack** [comment] 2015-12-13 17:54
@agpchil As @iqbalansari pointed you should be able to use `shell-quote-argument`. He would be better able to explain if you have any specific problems. I've tested following which seems to work perfectly with all my bookmarks(code is adapted from `mu4-alert` for testing purpose)

```elisp
(setq mu4e-bookmarks '(("flag:unread AND NOT flag:trashed"
                        "Unread messages"
                        97)
                       ("date:today..now"
                        "Today's messages"
                        116)
                       ("date:7d..now"
                        "Last 7 days"
                        119)
                       ("mime:image/*"
                        "Messages with images"
                        112)
                       ("tag:\\\\Inbox"
                        "Messages in Inbox"
                        105)
                       ("tag:\\\\Inbox AND flag:unread AND NOT flag:trashed"
                        "Unread Messages in Inbox"
                        117)))
(string-to-number
 (s-trim
  (shell-command-to-string
   (s-join " "
           (append (mapcar 'shell-quote-argument
                           (append
                            (list mu4e-mu-binary "find" "--nocolor")
                            (split-string (car (nth 4 mu4e-bookmarks)))))
                   '("2>/dev/null | wc -l"))))))
```

I'll checkout the newly pushed fix soon.

**Comment by agpchil** [comment] 2015-12-13 18:22
Oh well, I don't feel like implementing a full (and probably faulty) argument parser for that. But if you want to do it go ahead and send a PR afterwards :)

In the meantime, let me know if the latest changes works for you please.

**Comment by nixmaniack** [comment] 2015-12-14 06:12
@agpchil It worked only for this
```elisp
...
("mime:image/*"
 "Messages with images"
 112)
...
```
but not this
```elisp
("tag:\\\\Inbox"
 "Messages in Inbox"
 105)
("tag:\\\\Inbox AND flag:unread AND NOT flag:trashed"
  "Unread Messages in Inbox"
  117)
```
It'd fine if it's not working for last one as it already contains `flag:unread`, but it must work for `"tag:\\\\Inbox"`. Is there a simple way of printing what's getting executed apart from adding debug messages myself? 

Following is what should get executed in my case in the shell for expected results if it helps you.
```bash
bash-4.3$ mu find tag:\\\\Inbox | wc -l
      29
bash-4.3$ mu find tag:\\\\Inbox AND flag:unread | wc -l
      14
```

**Comment by agpchil** [comment] 2015-12-14 09:45
There is no extra debug functionality implemented in `mu4e-maildirs-extension` but you can quickly debug/eval anything in emacs anyway :)

If you prefer to add debug messages manually you probably want to add them at the end of the `mu4e-maildirs-extension-fetch` function (the mu command is built there).

**Comment by nixmaniack** [comment] 2015-12-14 13:06
I made following changes and it seems to work okay for me. May not be elegant but a hack to make things work. 
```diff
diff --git a/mu4e-maildirs-extension.el b/mu4e-maildirs-extension.el
index 08acc4b..277cd1c 100644
--- a/mu4e-maildirs-extension.el
+++ b/mu4e-maildirs-extension.el
@@ -356,7 +356,9 @@ If set to `nil' it won't be displayed."
 Optional call the function CALLBACK on finish."
   (let* ((eshell-special-chars-outside-quoting mu4e-maildirs-extension-special-chars-outside-quoting)
          (cmd (format mu4e-maildirs-extension-count-command-format
-                      (eshell-quote-argument query)))
+                      (s-join " "
+                              (append
+                               (mapcar 'shell-quote-argument (split-string query " "))))))
          (finish-func `(lambda(proc event)
                          (when (and (memq (process-status proc) '(exit))
                                     (buffer-live-p (process-buffer proc))
@@ -506,7 +508,7 @@ clicked."
 (defun mu4e-maildirs-extension-count (m key flags)
   "Fetch count results using mu FLAGS and store result in M plist with KEY"
   (let* ((path (plist-get m :path))
-         (query (format "maildir:\"%s\" %s" path flags))
+         (query (format "maildir:%s %s" path flags))
          (count (plist-get m key))
          (callback `(lambda(result)
                        (let ((m (--first (equal (plist-get it :path) ,path)
```

<img width="314" alt="bm" src="https://cloud.githubusercontent.com/assets/542810/11781693/82911336-a291-11e5-9efb-21affa1423dd.png">

**Comment by agpchil** [comment] 2015-12-14 14:46
Well, I just quickly tried your solution and it's not working for me. I think parsing the arguments based on whitespace is overly optimistic. For example, what happens if a maildir (or another argument) have spaces in the name? or already escaped spaces? (this is the issue I'm probably having, but maybe there are more cases too...)

I think parsing the arguments manually is hard and that's why I said I didn't feel like implementing a (faulty) parser :)

(If we could manage to successfully parse the arguments, I think we could also try to call the mu binary directly without the shell step.)

Let me know if you find a reliable way of parsing the arguments and fix this issue!

**Comment by nixmaniack** [comment] 2015-12-14 16:09
> I think parsing the arguments based on whitespace is overly optimistic.

I totally agree indeed. :smile: 
I just checked what queries were getting passed to shell and figured where I need to modify in `mu4e-maildirs-extension-fetch`. It would be better if we quote individual args before creating final command to pass to shell but I didn't try that due to lack of time. 

> what happens if a maildir (or another argument) have spaces in the name?

As you can see in the attached screenshot, I'm using the default config of `mu`, also I have maildirs with spaces with special chars as well e.g. `[Gmail].All Mail` and it seems to work out of the box with above change. Well as I said it's a hack in the end but it can be improved using shell-quoting appropriately.

> or already escaped spaces?
I haven't had a case where I had to manually escape space. As I explained my approach previously, I use `mu4e-headers-search` to form my queries and they should work.

For now if it's working fine for others, may be you can merge this at this point, I'll come back to it when I have enough time or someone else can look at it.

**Comment by iqbalansari** [comment] 2015-12-14 18:54
@agpchil Perhaps it would be better if `mu4e-mu-binary` is used to get path to the `mu`, instead of hardcoding the executable name `mu` in the command. The later assumes that `mu` is in `PATH` and the shell will be able to find it, which is not true for me atleast (I install `mu4e` via el-get).

I tried your `eshell` version as well as @nixmaniack's `shell-quote-argument` version. Both worked fine for me (though I am not sure about the robustness of `eshell-quote-argument` as opposed to `shell-quote-argument`)

**Comment by nwolfe** [comment] 2015-12-15 22:44
> To me this looks like a bug in mu4e-maildirs-extension. Can you check if still happens with latest changes or provide a step-by-step way to reproduce the problem?

I just pulled down your latest 2 commits to the `bookmarks`, so I'll keep an eye out for this behavior again and try to come up with a repro case if possible.

@agpchil What's the plan with this stuff now, in terms of a proper package release with bookmark support?  In the meantime I can continue to manually copy/paste the contents into my elpa/ (is there a better way?).

**Comment by agpchil** [comment] 2015-12-16 08:52
Well, the bookmarks branch seems to be broken. My latest commits didn't work for @nixmaniack and his changes didn't work for me either. Unfortunatly, I haven't had time to look at this yet.

Honestly, I can't merge this into master if it's not fully working. So things need to be fixed :) After that, if no other issues found, this should be merged into master (aka available in MELPA). And if no issues reported after a while it will be tagged/released for MELPA-stable.

> In the meantime I can continue to manually copy/paste the contents into my elpa/ (is there a better way?).

Manually copy/paste the contents looks like too much work to me :) If you want to keep following the latest changes in the `bookmarks` branch, I would probably just clone the git version, checkout the `bookmarks` branch and keep pulling changes. Or write a script to `curl/wget` the file directly. If you use QUELPA I think you can specify the repo/branch in you config too. But that's up to you :)

In response to @iqbalansari

> @agpchil Perhaps it would be better if mu4e-mu-binary is used to get path to the mu, instead of hardcoding the executable name mu in the command.

I agree. That was me being lazy as I already provided a defcustom to change the command.

> I tried your eshell version as well as @nixmaniack's shell-quote-argument version. Both worked fine for me (though I am not sure about the robustness of eshell-quote-argument as opposed to shell-quote-argument)

Do you have maildirs directories with special chars or spaces in their names?

Just to be clear, I'm not against `shell-quote-argument` itself. I'm concerned about parsing the arguments manually before passing them to `shell-quote-argument`.

**Comment by nwolfe** [comment] 2016-01-11 18:43
> Honestly, I can't merge this into master if it's not fully working.

@agpchil Could you hide bookmark support behind a variable and mark it as experimental or something?  
The current bookmark support works fine for me, and it would be really nice to stop maintaining this snowflake in my elpa/ :smile:

**Comment by agpchil** [comment] 2016-01-16 10:04
Sorry for the late reply.

> @agpchil Could you hide bookmark support behind a variable and mark it as experimental or something?

Someone suggested to allow enable/disable the bookmarks and maildirs using variables. That would be nice and we could try to do this by setting the variable as `risky`, but then I fear people would forget about this issue and it won't get fixed anymore :(

> The current bookmark support works fine for me, and it would be really nice to stop maintaining this snowflake in my elpa/

My quick fix didn't work for @nixmaniack and his diff didn't work for me :(

Even though his screenshot shows a maildir with spaces in their name working fine, it's not working for me.

I extracted the code in a function to simplify this example:

```lisp
(defun mu4e-maildirs-extension-quote (query)
  (s-join " "
          (append
           (mapcar 'shell-quote-argument (split-string query " ")))))
```

Running this function with a maildir query...

```lisp
(mu4e-maildirs-extension-quote "maildir:/account1/[Gmail].All Mail")
```
doesn't quote the space in the name:
```lisp
"maildir\\:/account1/\\[Gmail\\].All Mail"
```

**Comment by nwolfe** [comment] 2016-01-25 20:39
> Someone suggested to allow enable/disable the bookmarks and maildirs using variables. That would be nice and we could try to do this by setting the variable as risky, but then I fear people would forget about this issue and it won't get fixed anymore

On the other hand, if more people were exposed to the bookmark functionality you might get some contributions in fixing the problem.  Maybe getting more users involved will help diagnose the problem too.

If the problem we're dealing with is spaces in the names of folders (or something like that), and it's not reliably reproducible (at least it doesn't seem like it from your conversation), then maybe we could just document it as a known defect as part of the "risky"/experimental nature of bookmark support?

Just trying to make some headway on moving this stuff forward :smiley:

**Comment by agpchil** [comment] 2016-01-26 08:53
I just merged this on master with some small changes.

The issue with parsing the arguments is still there so the bookmarks feature is disabled by default. It can be enabled with:

```lisp
(setq mu4e-maildirs-extension-use-bookmarks t)
```
and the maildirs section can be disabled with:
```lisp
(setq mu4e-maildirs-extension-use-maildirs nil)
```


Also, `mu4e-mu-binary` is used for the command path (suggested by @iqbalansari).

Feel free to open new issues or contribute.
Thank you!

**Closed** 2016-01-26 09:02 UTC
